### PR TITLE
fix typo and add .flaskenv

### PR DESCRIPTION
**Pull request by guoard**

### CODE REVIEW

**Comment by vashian** [comment]
Hola!
let me first thank you because of fixing typos.

about .flaskenv ! as we have difference environments like db url and other things it's better to have separate env files
If you are ok Please delete .flaskenv ( or change the name of it.... it could be resource for an example env )

**Comment by guoard** [comment]
> Hola! let me first thank you because of fixing typos.
> 
> about .flaskenv ! as we have difference environments like db url and other things it's better to have separate env files If you are ok Please delete .flaskenv ( or change the name of it.... it could be resource for an example env )

ok but we need to update the README file to set an environment variable to run the Flask app

**Comment by guoard** [comment]
> Hola! let me first thank you because of fixing typos.
> 
> about .flaskenv ! as we have difference environments like db url and other things it's better to have separate env files If you are ok Please delete .flaskenv ( or change the name of it.... it could be resource for an example env )

but I think it should be there at least FLASK_APP=authz because I got an error when tried to run the app then I saw tutorials again and find out I should set this environment variable.

**Comment by vashian** [comment]
Ok I'll change my .env to .flaskenv

**Pull request merged**
